CREATE TABLE TBL_USERS (
  id            BIGSERIAL PRIMARY KEY,
  FIRST_NAME    VARCHAR   NOT NULL,
  LAST_NAME     VARCHAR   NOT NULL,
  USERNAME      VARCHAR   NOT NULL,
  EMAIL         VARCHAR   NOT NULL,
  PHONE_NUMBER  VARCHAR   NOT NULL,
  HASH_PASSWORD VARCHAR   NOT NULL
);